FORMAT: 1A
HOST: https://paperhub.io/dev/backend/branches/master

# PaperHub API v0

# Group Users
User related resources of the *PaperHub API*.

## User [/users/{id}]
+ Model (application/json)
    + Body

            {
              "_id": "54db502f8a9e25e834e3c3f4",
              "username": "andrenarchy",
              "familyName": "Gaul",
              "givenNames": "André",
              "displayName": "André Gaul",
              "email": "andre@gaul.io",
              "gravatarMd5": "daa7eedcfae667756a452c79d4b30d6a",
              "accounts": [
                {
                  "_id": "54db502f8a9e25e834e3c3f5",
                  "id": "0000-0003-2977-4037",
                  "type": "orcid"
                }
              ],
              "firstSignin": false,
              "settings": {
                "remember": true
              },
              "createdAt": "2015-02-11T12:50:55.283Z",
              "updatedAt": "2015-03-09T14:47:59.938Z"
            }

### Retrieve a user [GET]
+ Response 200 (application/json)
    + Body

            {
              "_id": "54db502f8a9e25e834e3c3f4",
              "username": "andrenarchy",
              "familyName": "Gaul",
              "givenNames": "André",
              "displayName": "André Gaul",
              "email": "andre@gaul.io",
              "gravatarMd5": "daa7eedcfae667756a452c79d4b30d6a",
              "accounts": [
                {
                  "_id": "54db502f8a9e25e834e3c3f5",
                  "id": "0000-0003-2977-4037",
                  "type": "orcid"
                }
              ],
              "firstSignin": false,
              "settings": {
                "remember": true
              },
              "createdAt": "2015-02-11T12:50:55.283Z",
              "updatedAt": "2015-03-09T14:47:59.938Z"
            }

+ Request
    + Headers

            X-Auth-Token: e1289dd4dec21ddfef4672fa23906f20
    
+ Response 200
    [User][]

### Update a user [PUT]
+ Request (application/json)
    + Headers

            X-Auth-Token: e1289dd4dec21ddfef4672fa23906f20

    + Body

            {
              "username": "andrenarchy",
              "familyName": "Gaul",
              "givenNames": "André",
              "displayName": "André Gaul",
              "settings": {
                "remember": true
              },
            }

+ Response 200
    [User][]
            

## ORCID sync [/users/{id}/syncFromOrcid/{orcidId}]

### Update user from linked ORCID account [PUT]
+ Response 200
    [User][]


# Group Articles

## Article [/articles/{id}]
+ Model (application/json)
    + Body

            {
              "_id": "54f480d81217ec3c49af08a3",
              "title": "Preconditioned Recycling Krylov subspace methods for self-adjoint problems",
              "authors": [
                "André Gaul",
                "Nico Schlömer"
              ],
              "publishedAt": "2015-01-07T17:08:36.000Z",
              "abstract": "The authors propose a recycling...",
              "tags": [
                "math.NA",
                "physics.comp-ph",
                "65F10, 65F08, 35Q55, 35Q56"
              ],
              "public": true,
              "source": {
                "url": "http://arxiv.org/abs/1208.0264v4",
                "name": "arXiv.org",
                "id": "1208.0264v4",
                "type": "arxiv"
              },
              "file": {
                "sha": "748b8dcc0eebe4b3ba6345f80bdfc86d36118fe5",
                "url": "http://localhost:8000/proxy?url=http%3A%2F%2Farxiv.org%2Fpdf%2F1208.0264v4.pdf"
              },
              "importedBy": {
                "_id": "54db502f8a9e25e834e3c3f4",
                "username": "andrenarchy",
                "displayName": "André Gaul",
                "gravatarMd5": "ad928555ed989896aeaeb2b88db2163f"
              },
              "createdAt": "2015-03-02T15:25:15.681Z",
              "updatedAt": "2015-03-02T15:25:15.681Z"
            }

### Retrieve article [GET]
+ Response 200
    [Article][]

## Import from approved sources [/articles/sources]

### Test if article can be imported [GET]
+ Request (application/json)
    + Headers
    
            X-Auth-Token: e1289dd4dec21ddfef4672fa23906f20

+ Response 200 (application/json)
    + Body

            {
              "publishedAt": "2014-06-12T13:55:10Z",
              "authors": [
                "André Gaul",
                "Nico Schlömer"
              ],
              "source": {
                "id": "1208.0264v3",
                "type": "arxiv"
              },
              "abstract": "The authors propose a recycling Krylov subspace method for the solution of a\nsequence of self-adjoint linear systems. Such problems appear, for example, in\nthe Newton process for solving nonlinear equations. Ritz vectors are\nautomatically extracted from one MINRES run and then used for self-adjoint\ndeflation in the next. The method is designed to work with arbitrary inner\nproducts and arbitrary self-adjoint positive-definite preconditioners whose\ninverse can be computed with high accuracy. Numerical experiments with\nnonlinear Schr\\\"odinger equations indicate a substantial decrease in\ncomputation time when recycling is used.",
              "title": "Preconditioned Recycling Krylov subspace methods for self-adjoint problems",
              "tags": [
                "math.NA",
                "physics.comp-ph",
                "65F10, 65F08, 35Q55, 35Q56"
              ],
              "public": true
            }
            
### Import article [POST]
+ Request
    + Headers
    
            X-Auth-Token: e1289dd4dec21ddfef4672fa23906f20

+ Response 200
    [Article][]